import * as React from "react";
import * as Types from "./types";

declare function SectionKitInfo(props: {
  as?: React.ElementType;
  stylesTheme?: Types.Builtin.Text;
  stylesPaddingTop?: Types.Builtin.Text;
  stylesPaddingBottom?: Types.Builtin.Text;
  eyebrowEyebrowVisibility?: Types.Visibility.VisibilityConditions;
  eyebrowEyebrowText?: Types.Basic.RichTextChildren;
  eyebrowEyebrowMaxWidth?: Types.Builtin.Text;
  headingHeadingVisibility?: Types.Visibility.VisibilityConditions;
  headingHeadingText?: Types.Basic.RichTextChildren;
  headingHeadingMaxWidth?: Types.Builtin.Text;
  paragraphParagraphVisibility?: Types.Visibility.VisibilityConditions;
  paragraphParagraphText?: Types.Basic.RichTextChildren;
  paragraphParagraphMaxWidth?: Types.Builtin.Text;
  buttonGroupButtonGroupVisibility?: Types.Visibility.VisibilityConditions;
  button1Button1Visibility?: Types.Visibility.VisibilityConditions;
  button1Button1Text?: React.ReactNode;
  button1Button1Link?: Types.Basic.Link;
  button2Button2Visibility?: Types.Visibility.VisibilityConditions;
  button2Button2Text?: React.ReactNode;
  button2Button2Link?: Types.Basic.Link;
  mainVisualMainImageVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualMainImageFile?: Types.Asset.Image;
  mainVisualMainImageAltText?: Types.Basic.AltText;
  mainVisualMainImageLoading?: Types.Builtin.Text;
  mainVisualMainVideoVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualMainVideoUrl?: Types.Builtin.Text;
  headingStyle?: Types.Builtin.Text;
  eyebrowStyles?: Types.Builtin.Text;
  stylesSectionHeight?: Types.Builtin.Text;
  paragraphStyless?: Types.Builtin.Text;
  tab1ParagraphRichText?: Types.Basic.RichTextChildren;
  tab2Paragraph?: Types.Basic.RichTextChildren;
  tab3ParagraphR?: Types.Basic.RichTextChildren;
  tab4ParagraphRich?: Types.Basic.RichTextChildren;
  tab1LeftText?: Types.Basic.RichTextChildren;
}): React.JSX.Element;
