import * as React from "react";
import * as Types from "./types";

declare function SectionHeroInternalPage(props: {
  as?: React.ElementType;
  stylesTheme?: Types.Builtin.Text;
  eyebrowEyebrowVisibility?: Types.Visibility.VisibilityConditions;
  eyebrowEyebrowText?: Types.Basic.RichTextChildren;
  eyebrowEyebrowMaxWidth?: Types.Builtin.Text;
  headingHeadingVisibility?: Types.Visibility.VisibilityConditions;
  headingHeadingText?: Types.Basic.RichTextChildren;
  headingHeadingMaxWidth?: Types.Builtin.Text;
  paragraphParagraphVisibility?: Types.Visibility.VisibilityConditions;
  paragraphParagraphText?: Types.Basic.RichTextChildren;
  paragraphParagraphMaxWidth?: Types.Builtin.Text;
  buttonGroupButtonGroupVisibility?: Types.Visibility.VisibilityConditions;
  button1Button1Visibility?: Types.Visibility.VisibilityConditions;
  button1Button1Text?: React.ReactNode;
  button1Button1Link?: Types.Basic.Link;
  button2Button2Visibility?: Types.Visibility.VisibilityConditions;
  button2Button2Text?: React.ReactNode;
  button2Button2Link?: Types.Basic.Link;
  mainVisualMainImageVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualMainImageFile?: Types.Asset.Image;
  mainVisualMainImageAltText?: Types.Basic.AltText;
  mainVisualMainImageLoading?: Types.Builtin.Text;
  mainVisualMainVideoVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualMainVideoUrl?: Types.Builtin.Text;
  mainVisual2ColumnVisualSliderVisibility?: Types.Visibility.VisibilityConditions;
  headingStyle?: Types.Builtin.Text;
  eyebrowStyles?: Types.Builtin.Text;
  paragraphStyless?: Types.Builtin.Text;
  mainVisualSingleVisualVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualBackgroundVisualVisibility?: Types.Visibility.VisibilityConditions;
  mainVisualVisualVisibility?: Types.Visibility.VisibilityConditions;
  stylesPaddingTop?: Types.Builtin.Text;
  stylesPaddingBottom?: Types.Builtin.Text;
  stylesSpecialSpacing?: Types.Builtin.Text;
  eyebrowPlainText?: React.ReactNode;
  eyebrowPlainTextVisibiliity?: Types.Visibility.VisibilityConditions;
  eyebrowRichTextVisibility?: Types.Visibility.VisibilityConditions;
  eyebrowFeaturedText?: React.ReactNode;
  eyebrowEyebrowIconViewbox?: Types.Builtin.Text;
  eyebrowIconPath1?: Types.Builtin.Text;
  faqFaqItemVisibility?: Types.Visibility.VisibilityConditions;
  faqFaqLongAnswer?: Types.Basic.RichTextChildren;
  stylesIsBackgroundColor?: Types.Builtin.Text;
  variant?: "Base" | "Text Content Full Width" | "Top Aligned";
  contactFormContactFormVisibility?: Types.Visibility.VisibilityConditions;
  paragraphParagraphStyles?: Types.Builtin.Text;
  elementQuestion?: React.ReactNode;
  mainVisualVisualPosition?: Types.Builtin.Text;
  slot?: Types.Slots.SlotContent;
  linkedinIconWrapVisibility?: Types.Visibility.VisibilityConditions;
  slot?: Types.Slots.SlotContent;
  socialMediaIconsVisibility?: Types.Visibility.VisibilityConditions;
  slot?: Types.Slots.SlotContent;
}): React.JSX.Element;
